# Generated by Django 3.2.6 on 2021-09-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='downs',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='postID',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='stock',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='ups',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='url',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='numComments',
            field=models.IntegerField(blank=True),
        ),
    ]
