# Generated by Django 3.2.6 on 2021-09-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_api', '0002_auto_20210902_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='url',
            new_name='postURL',
        ),
    ]
